<script setup></script>

<template>
  <main>
    <h1>Data project</h1>
    <br />
    <h2>Project: Bellabeat Case study</h2>

    <div>
      <h3>Project Overview</h3>
      <p>
        Objective in this analysis is to gain insights from data on women using
        non-Bellabeat smart devices to understand current trends and usage
        patterns.
      </p>
    </div>

    <div>
      <h3>Data sources</h3>
      <p>
        Data to analysis in this case was<a
          href="https://www.kaggle.com/datasets/arashnic/fitbit"
          target="_blank"
          rel="noopener noreferrer"
          >Fitbit Fitness Tracker Data</a
        >
        from Kaggle that made available through Mobius and have license of CC0:
        Public Domain and were generated by respondents to a distributed survey
        via Amazon Mechanical Turk
      </p>
    </div>

    <div>
      <h3>My Analysis</h3>

   
    <div class="main video-container">
      <div
        style="
          position: relative;
          width: 100%;
          height: 0;
          padding-top: 56.25%;
          padding-bottom: 0;
          box-shadow: 0 2px 8px 0 rgba(63, 69, 81, 0.16);
          margin-top: 1.6em;
          margin-bottom: 0.9em;
          overflow: hidden;
          border-radius: 8px;
          will-change: transform;
        "
      >
        <iframe
          loading="lazy"
          style="
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            border: none;
            padding: 0;
            margin: 0;
          "
          src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGLeq71fLk&#x2F;mOLBfVpK0VbRaZts2Q01vQ&#x2F;view?embed"
          allowfullscreen="allowfullscreen"
          allow="fullscreen"
        >
        </iframe>
      </div>
      <a
        href="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGLeq71fLk&#x2F;mOLBfVpK0VbRaZts2Q01vQ&#x2F;view?utm_content=DAGLeq71fLk&amp;utm_campaign=designshare&amp;utm_medium=embeds&amp;utm_source=link"
        target="_blank"
        rel="noopener"
        >Data Analysis on Case Study Bellabeat</a
      >
      by pattera jong
    </div>

</div>
    <a
      href="https://www.kaggle.com/code/patterajong/case-study-bellabeat/notebook"
      target="_blank"
    >
      See more on my Kaggle! -></a
    >
  </main>
</template>

<style scoped>
a:hover {
  font-size: medium;
  padding: 5px;
}
h2 {
  font-size: 1.4rem;
  font-weight: 600;
  color: var(--color-heading);
}

h3 {
  font-size: 1.3rem;
  font-weight: 500;
  margin: 1.7rem 0rem 0.7rem 0rem;
  color: var(--color-heading);
}
</style>
